export const ROUTES = {
  home: '/',
  login: '/login',
  register: '/register',
  verifyEmail: '/verify-email',
  forgotPassword: '/forgot-password',
  resetPassword: '/reset-password',
  inviteMember: '/invite/member',
  inviteEmployee: '/invite/employee',
  /** Legacy paths from invitation emails (keep for old links) */
  acceptMemberInvite: '/accept-member-invite',
  acceptEmployeeInvite: '/accept-employee-invite',
  admin: {
    root: '/admin',
    dashboard: '/admin/dashboard',
    company: '/admin/company',
    members: '/admin/members',
    employees: '/admin/employees',
    extraShifts: '/admin/extra-shifts',
    unlockRequests: '/admin/unlock-requests',
    attendance: '/admin/attendance',
    verification: '/admin/verification',
    reports: '/admin/reports',
    attendanceDetail: '/admin/attendance/record',
  },
  member: {
    root: '/member',
    dashboard: '/member/dashboard',
    attendance: '/member/attendance',
    reports: '/member/reports',
    profile: '/member/profile',
    attendanceDetail: '/member/attendance/record',
  },
  employee: {
    root: '/employee',
    dashboard: '/employee/dashboard',
    profile: '/employee/profile',
    attendance: '/employee/attendance',
    attendanceHistory: '/employee/attendance/history',
    attendanceDetail: '/employee/attendance/record',
    unlockRequests: '/employee/unlock-requests',
  },
};
